### ISSUE TITLE
增加 ActivityResultLauncher 支持

### ISSUE THREAD

**Issue by MycroftWong** [BillyWei01/EasyAlbum#9]
如题，有个需求是在需要监听 album 的关闭，当然这个可以特殊处理。但是如果加上 ActivityResultLauncher 支持最好，可以自定义 ActivityResultContract，在 ActivityResultContract 中增加启动 album 时的参数。

**Comment by BillyWei01** [comment]
你们目前是正在用EasyAlbum吗

**Comment by MycroftWong** [comment]
> 你们目前是正在用EasyAlbum吗

嗯是的

**Comment by BillyWei01** [comment]
给Request增加了一个AlbumListener的接口类，留了一个onAlbumClose方法，用于监听album关闭。
诚如文章 https://juejin.cn/post/7215163152907092024 中提到的，EasyAlbum是通过静态变量来传递结果的，所以不适合用ActivityResult那一套。
如果需要ActivityResultLauncher那一套的话可folk源码自行改造，毕竟源码也不是很复杂。

**Comment by MycroftWong** [comment]
> 给Request增加了一个AlbumListener的接口类，留了一个onAlbumClose方法，用于监听album关闭。 诚如文章 https://juejin.cn/post/7215163152907092024 中提到的，EasyAlbum是通过静态变量来传递结果的，所以不适合用ActivityResult那一套。 如果需要ActivityResultLauncher那一套的话可folk源码自行改造，毕竟源码也不是很复杂。

谢谢大佬，在用了
